name: hnybdrop
main: com.hyperfaststudio.hnybdrop.HnybDrop
version: 1.0
api-version: 1.16
author: HyperFastStudio
commands:
  hnybdrop:
    description: Bật/tắt, reload và kiểm tra cập nhật plugin.
    usage: /<command> <on|off|reload|checkupdate>
  drop:
    description: Alias của lệnh hnybdrop.
    usage: /<command> <on|off|reload|checkupdate>
permissions:
  hnybdrop.use:
    description: Cho phép sử dụng các lệnh cơ bản của hnybdrop.
    default: op
  hnybdrop.admin:
    description: Cho phép sử dụng lệnh reload và checkupdate.
    default: false
