#    ██╗  ██╗███╗   ██╗██╗   ██╗██████╗
#    ██║  ██║████╗  ██║╚██╗ ██╔╝██╔══██╗
#    ███████║██╔██╗ ██║ ╚████╔╝ ██████╔╝
#    ██╔══██║██║╚██╗██║  ╚██╔╝  ██╔══██╗
#    ██║  ██║██║ ╚████║   ██║   ██████╔╝
#    ╚═╝  ╚═╝╚═╝  ╚═══╝   ╚═╝   ╚═════╝

# Sản phẩm của HyperFast Studio
# Các thông tin :
#  - Minecraft Server : PC : quackmc.net, PE : quackmc.net (Port: 19132)
#  - Web : www.quackmc.net
#  - Discord : discord.gg/quackmc


  # Bật/tắt chức năng xác nhận vứt vật phẩm
confirm-enabled: true

# Khoảng thời gian xác nhận (miligiây)
confirm-interval: 10000

messages:
  drop-first-attempt: "&eNhấn vứt lần đầu, sau đó nhấn lại trong 10 giây để xác nhận vứt."
  drop-confirmed: "&aBạn đã xác nhận vứt vật phẩm."
  enabled-message: "&aChức năng xác nhận vứt đã được bật."
  disabled-message: "&cChức năng xác nhận vứt đã được tắt."
  help-message: |
    - &6/hnybdrop on: &aBật chức năng xác nhận vứt.
    - &6/hnybdrop off: &cTắt chức năng xác nhận vứt.
    - &6/hnybdrop reload: &eReload cấu hình plugin (yêu cầu perm hnybdrop.admin).
    - &6/hnybdrop checkupdate: &eKiểm tra cập nhật plugin (yêu cầu perm hnybdrop.admin).
    - &6/drop: &7Alias của lệnh hnybdrop.
  no-permission: "&cBạn không có quyền sử dụng lệnh này."
  invalid-argument: "&cLệnh không hợp lệ."
